services:
  ros-human-sensing:
    image: ghcr.io/airesearchlab/ros-human-sensing:humble
    restart: unless-stopped
    privileged: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]   
    volumes:
      - type: volume              
        source: system
        target: /system
      # - type: bind                              ---> for custom weights
      #   source: ./weights
      #   target: /system/weights

volumes:
  system: