yolo_ros_node:
  ros__parameters:
    yolo_model: "yolov9s.pt"
    input_rgb_topic: "/camera/color/image_raw"
    input_depth_topic: "/camera/depth/points"
    subscribe_depth: True
    publish_annotated_image: True
    annotated_topic: "/yolo_ros/annotated_image"
    detailed_topic: "/yolo_ros/detection_result"
    threshold: 0.25
    device: "0"

boxmot_ros_node:
  ros__parameters:
    tracking_model: "deepocsort"
    reid_model: "osnet_x0_25_msmt17.pt"
    input_topic: "/yolo_ros/detection_result"
    publish_annotated_image: True
    annotated_topic: "/boxmot_ros/annotated_image"
    detailed_topic: "/boxmot_ros/tracking_result"
    threshold: 0.25
    device: "0"